### ISSUE TITLE
Local Hedera Network

### ISSUE THREAD

**Issue by joan41868** [LimeChain/hardhat-hethers#17]
In order to enable local smart contract development, `hardhat-hethers` should support creating a local hedera network.
The network must consist of consensus nodes and a mirror node.

Notes:
- the first time the network is created is going to be slow
- secondary network launches should be faster

Resources:
- network repo: https://github.com/hashgraph/hedera-network-e2e

**Comment by Daniel-K-Ivanov** [comment]
https://hardhat.org/hardhat-network/#hardhat-network
